# Incidence of influenza-like illness in France

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import isoweek

The data on the incidence of influenza-like illness are available from the Web site of the [RÃ©seau Sentinelles](http://www.sentiweb.fr/). We download them as a file in CSV format, in which each line corresponds to a week in the observation period. Only the complete dataset, starting in 1984 and ending with a recent week, is available for download.

In [4]:
data_url = "http://www.sentiweb.fr/datasets/incidence-PAY-3.csv"

This is the documentation of the data from [the download site](https://ns.sentiweb.fr/incidence/csv-schema-v1.json):

| Column name  | Description                                                                                                               |
|--------------|---------------------------------------------------------------------------------------------------------------------------|
| `week`       | ISO8601 Yearweek number as numeric (year times 100 + week nubmer)                                                               |
| `indicator`  | Unique identifier of the indicator, see metadata document https://www.sentiweb.fr/meta.json                               |
| `inc`        | Estimated incidence value for the time step, in the geographic level                                                      |
| `inc_low`    | Lower bound of the estimated incidence 95% Confidence Interval                                                            |
| `inc_up`     | Upper bound of the estimated incidence 95% Confidence Interval                                                            |
| `inc100`     | Estimated rate incidence per 100,000 inhabitants                                                                          |
| `inc100_low` | Lower bound of the estimated incidence 95% Confidence Interval                                                            |
| `inc100_up`  | Upper bound of the estimated rate incidence 95% Confidence Interval                                                       |
| `geo_insee`  | Identifier of the geographic area, from INSEE https://www.insee.fr                                                        |
| `geo_name`   | Geographic label of the area, corresponding to INSEE code. This label is not an id and is only provided for human reading |

The first line of the CSV file is a comment, which we ignore with `skip=1`.

# We want to replace the following code:
raw_data = pd.read_csv(data_url, encoding = 'iso-8859-1', skiprows=1)\
raw_data

# With code that does the following instead:
1. If the local file does not exist, download the data and put them into the local file
2. Read the local CSV file.\
Performed in next code block:

In [18]:
file_url = "https://www.sentiweb.fr/datasets/all/inc-3-PAY.csv"
file_name = "inc-3-PAY.csv"

try:
    raw_data = pd.read_csv(file_name, encoding = 'iso-8859-1', skiprows=1)
except:
    df = pd.read_csv(data_url, encoding = 'iso-8859-1', skiprows=1)
    raw_data = df.to_csv(file_name)
    
raw_data

,0,202450,3,145230,132961.0,157499.0,218,200.0,236.0,FR,France
0,1,202449,3,108971,99421.0,118521.0,163,149.0,177.0,FR,France
1,2,202448,3,87611,78896.0,96326.0,131,118.0,144.0,FR,France
2,3,202447,3,76286,67626.0,84946.0,114,101.0,127.0,FR,France
3,4,202446,3,56399,49006.0,63792.0,85,74.0,96.0,FR,France
4,5,202445,3,47347,40843.0,53851.0,71,61.0,81.0,FR,France
5,6,202444,3,36039,30122.0,41956.0,54,45.0,63.0,FR,France
6,7,202443,3,46572,39928.0,53216.0,70,60.0,80.0,FR,France
7,8,202442,3,67785,60009.0,75561.0,102,90.0,114.0,FR,France
8,9,202441,3,79435,71386.0,87484.0,119,107.0,131.0,FR,France
9,10,202440,3,84965,76555.0,93375.0,127,114.0,140.0,FR,France
10,11,202439,3,91660,82937.0,100383.0,137,124.0,150.0,FR,France
11,12,202438,3,91786,82903.0,100669.0,138,125.0,151.0,FR,France
12,13,202437,3,56460,49319.0,63601.0,85,74.0,96.0,FR,France
13,14,202436,3,33657,27906.0,39408.0,50,41.0,59.0,FR,France
14,15,202435,3,27404,22036.0,32772.0,41,33.0,49.0,FR,France
15,16,202434,3,26717,21003.0,32431.0,40,31.0,49.0,FR,France
16,17,202433,3,20623,15349.0,25897.0,31,23.0,39.0,FR,France
17,18,202432,3,23187,17532.0,28842.0,35,27.0,43.0,FR,France
18,19,202431,3,26035,20267.0,31803.0,39,30.0,48.0,FR,France
19,20,202430,3,36393,28593.0,44193.0,55,43.0,67.0,FR,France
20,21,202429,3,39560,32592.0,46528.0,59,49.0,69.0,FR,France
21,22,202428,3,54342,45781.0,62903.0,81,68.0,94.0,FR,France
22,23,202427,3,47364,40234.0,54494.0,71,60.0,82.0,FR,France
23,24,202426,3,44219,36956.0,51482.0,66,55.0,77.0,FR,France
24,25,202425,3,47204,40300.0,54108.0,71,61.0,81.0,FR,France
25,26,202424,3,41110,34671.0,47549.0,62,52.0,72.0,FR,France
26,27,202423,3,35875,30610.0,41140.0,54,46.0,62.0,FR,France
27,28,202422,3,33772,28274.0,39270.0,51,43.0,59.0,FR,France
28,29,202421,3,21963,17556.0,26370.0,33,26.0,40.0,FR,France
29,30,202420,3,20057,15780.0,24334.0,30,24.0,36.0,FR,France
...,...,...,...,...,...,...,...,...,...,...,...
2063,2064,198521,3,26096,19621.0,32571.0,47,35.0,59.0,FR,France
2064,2065,198520,3,27896,20885.0,34907.0,51,38.0,64.0,FR,France
2065,2066,198519,3,43154,32821.0,53487.0,78,59.0,97.0,FR,France
2066,2067,198518,3,40555,29935.0,51175.0,74,55.0,93.0,FR,France
2067,2068,198517,3,34053,24366.0,43740.0,62,44.0,80.0,FR,France
2068,2069,198516,3,50362,36451.0,64273.0,91,66.0,116.0,FR,France
2069,2070,198515,3,63881,45538.0,82224.0,116,83.0,149.0,FR,France
2070,2071,198514,3,134545,114400.0,154690.0,244,207.0,281.0,FR,France
2071,2072,198513,3,197206,176080.0,218332.0,357,319.0,395.0,FR,France
2072,2073,198512,3,245240,223304.0,267176.0,445,405.0,485.0,FR,France
2073,2074,198511,3,276205,252399.0,300011.0,501,458.0,544.0,FR,France
2074,2075,198510,3,353231,326279.0,380183.0,640,591.0,689.0,FR,France
2075,2076,198509,3,369895,341109.0,398681.0,670,618.0,722.0,FR,France
2076,2077,198508,3,389886,359529.0,420243.0,707,652.0,762.0,FR,France
2077,2078,198507,3,471852,432599.0,511105.0,855,784.0,926.0,FR,France
2078,2079,198506,3,565825,518011.0,613639.0,1026,939.0,1113.0,FR,France
2079,2080,198505,3,637302,592795.0,681809.0,1155,1074.0,1236.0,FR,France
2080,2081,198504,3,424937,390794.0,459080.0,770,708.0,832.0,FR,France
2081,2082,198503,3,213901,174689.0,253113.0,388,317.0,459.0,FR,France
2082,2083,198502,3,97586,80949.0,114223.0,177,147.0,207.0,FR,France
2083,2084,198501,3,85489,65918.0,105060.0,155,120.0,190.0,FR,France
2084,2085,198452,3,84830,60602.0,109058.0,154,110.0,198.0,FR,France
2085,2086,198451,3,101726,80242.0,123210.0,185,146.0,224.0,FR,France
2086,2087,198450,3,123680,101401.0,145959.0,225,184.0,266.0,FR,France
2087,2088,198449,3,101073,81684.0,120462.0,184,149.0,219.0,FR,France
2088,2089,198448,3,78620,60634.0,96606.0,143,110.0,176.0,FR,France
2089,2090,198447,3,72029,54274.0,89784.0,131,99.0,163.0,FR,France
2090,2091,198446,3,87330,67686.0,106974.0,159,123.0,195.0,FR,France
2091,2092,198445,3,135223,101414.0,169032.0,246,184.0,308.0,FR,France
2092,2093,198444,3,68422,20056.0,116788.0,125,37.0,213.0,FR,France

Are there missing data points? Yes, week 19 of year 1989 does not have any observed values.

In [10]:
raw_data[raw_data.isnull().any(axis=1)]

         0  202450  3 145230  132961.0  157499.0 218  200.0  236.0  FR  France
1856  1857  198919  3      -       NaN       NaN   -    NaN    NaN  FR  France

We delete this point, which does not have big consequence for our rather simple analysis.

In [ ]:
data = raw_data.dropna().copy()
data

Our dataset uses an uncommon encoding; the week number is attached
to the year number, leaving the impression of a six-digit integer.
That is how Pandas interprets it.

A second problem is that Pandas does not know about week numbers.
It needs to be given the dates of the beginning and end of the week.
We use the library `isoweek` for that.

Since the conversion is a bit lengthy, we write a small Python 
function for doing it. Then we apply it to all points in our dataset. 
The results go into a new column 'period'.

In [ ]:
def convert_week(year_and_week_int):
    year_and_week_str = str(year_and_week_int)
    year = int(year_and_week_str[:4])
    week = int(year_and_week_str[4:])
    w = isoweek.Week(year, week)
    return pd.Period(w.day(0), 'W')

data['period'] = [convert_week(yw) for yw in data['week']]

There are two more small changes to make.

First, we define the observation periods as the new index of
our dataset. That turns it into a time series, which will be
convenient later on.

Second, we sort the points chronologically.

In [ ]:
sorted_data = data.set_index('period').sort_index()

We check the consistency of the data. Between the end of a period and
the beginning of the next one, the difference should be zero, or very small.
We tolerate an error of one second.

This is OK except for one pair of consecutive periods between which
a whole week is missing.

We recognize the dates: it's the week without observations that we
have deleted earlier!

In [ ]:
periods = sorted_data.index
for p1, p2 in zip(periods[:-1], periods[1:]):
    delta = p2.to_timestamp() - p1.end_time
    if delta > pd.Timedelta('1s'):
        print(p1, p2)

A first look at the data!

In [ ]:
sorted_data['inc'].plot()

A zoom on the last few years shows more clearly that the peaks are situated in winter.

In [ ]:
sorted_data['inc'][-200:].plot()

## Study of the annual incidence

Since the peaks of the epidemic happen in winter, near the transition
between calendar years, we define the reference period for the annual
incidence from August 1st of year $N$ to August 1st of year $N+1$. We
label this period as year $N+1$ because the peak is always located in
year $N+1$. The very low incidence in summer ensures that the arbitrariness
of the choice of reference period has no impact on our conclusions.

Our task is a bit complicated by the fact that a year does not have an
integer number of weeks. Therefore we modify our reference period a bit:
instead of August 1st, we use the first day of the week containing August 1st.

A final detail: the dataset starts in October 1984, the first peak is thus
incomplete, We start the analysis with the first full peak.

In [ ]:
first_august_week = [pd.Period(pd.Timestamp(y, 8, 1), 'W')
                     for y in range(1985,
                                    sorted_data.index[-1].year)]

Starting from this list of weeks that contain August 1st, we obtain intervals of approximately one year as the periods between two adjacent weeks in this list. We compute the sums of weekly incidences for all these periods.

We also check that our periods contain between 51 and 52 weeks, as a safeguard against potential mistakes in our code.

In [ ]:
year = []
yearly_incidence = []
for week1, week2 in zip(first_august_week[:-1],
                        first_august_week[1:]):
    one_year = sorted_data['inc'][week1:week2-1]
    assert abs(len(one_year)-52) < 2
    yearly_incidence.append(one_year.sum())
    year.append(week2.year)
yearly_incidence = pd.Series(data=yearly_incidence, index=year)

And here are the annual incidences.

In [ ]:
yearly_incidence.plot(style='*')

A sorted list makes it easier to find the highest values (at the end).

In [ ]:
yearly_incidence.sort_values()

Finally, a histogram clearly shows the few very strong epidemics, which affect about 10% of the French population,
but are rare: there were three of them in the course of 35 years. The typical epidemic affects only half as many people.

In [ ]:
yearly_incidence.hist(xrot=20)